In [2]:
import numpy as np
matrix_A =np.array([[1,2,3],
                   [3,4,5]])
matrix_B =np.array([[6,7,8],  
                   [9,10,11]])
matrix_sum= matrix_A + matrix_B
print(matrix_A)
print(matrix_B)
print(matrix_sum)


[[1 2 3]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 7  9 11]
 [12 14 16]]


In [3]:
import numpy as np
matrix_A =np.array([[1,2,3],
                   [3,4,5]])
matrix_B =np.array([[6,7,8],  
                   [9,10,11]])
matrix_difference = matrix_A - matrix_B
print(matrix_A)
print(matrix_B)
print(matrix_difference)


[[1 2 3]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[-5 -5 -5]
 [-6 -6 -6]]
